# Generated by Django 3.2.7 on 2021-10-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_timestamp_contact_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='created',
        ),
    ]
