# Generated by Django 3.2.7 on 2021-10-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('PQ', 'Product Query'), ('DL', 'Deliveries'), ('RR', 'Repair Request'), ('CM', 'Complaint'), ('OR', 'Other...')], max_length=2),
        ),
    ]
