# Generated by Django 3.2.7 on 2021-10-23 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20210728_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fixed_it',
            field=models.ManyToManyField(related_name='fixed_its', to=settings.AUTH_USER_MODEL),
        ),
    ]
